version: '3.9'

services:
  bot:
    image: yanturnt/tg-bot:latest
    container_name: tg-bot
    restart: always
    env_file:
      - .env
    command: ['node', 'dist/bot.js']

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 tg-bot
